### ISSUE TITLE
Res and Req are not compatible w/ express res and req

### ISSUE THREAD

**Issue by RavenHursT** [vkurchatkin/koa-connect#1]
Was trying to use https://github.com/graphql/express-graphql and keep getting "response.status is not a function" errors.  AFAIK, the reason for this is that `c2k()` is passing the Koa req and res objects through to the Express middleware and they aren't compatible w/ Express's req and resp.

From what I see is that c2k needs to find a way "convert" the koa req and res objects to Express objects so that middleware operating on those objects will work.

**Comment by vkurchatkin** [comment]
It is kind of expected, since this is `koa-connect`, not `koa-express`. `koa-express` exists and probably does what you want, so you should check it out.

**Comment by RavenHursT** [comment]
Oh.. my mistake.. I thought Express was built on top of Connect.

**Comment by RavenHursT** [comment]
oops.. this was indeed the wrong repo.. my bad.

**Comment by RavenHursT** [comment]
Ok.. confused..

Looks like koa-express is a fork off of koa-connect... That why I thought they were related and I created a comment here.  

https://github.com/dougmoscrop/koa-express

@dougmoscrop must be looking to do something similar for express utilizing this project as a starting point.

**Comment by dougmoscrop** [comment]
I needed to call `next` with an error, calling it koa-express was dumb on my part. I'm open to pull requests if you want to try and make it express for real :P

**Comment by RavenHursT** [comment]
:+1: 

Correct me if I'm wrong, but it would essentially just be an effort to mock out express req and resp objects from Koa req and resp objects.  Right?

**Comment by dougmoscrop** [comment]
At the surface, yep. I think maybe open an issue on my fork, ideally with sample middleware that you're trying to use and we can chat there.
