### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by aaronbeall** [vkurchatkin/koa-connect#11]
There doesn't seem to be any `@types/koa-connect` package. Can we add TypeScript definitions to this project?

**Comment by lourd** [comment]
Thanks for the suggestion. Sure, I'd support that. I would also support going ahead and writing the source in typescript. Either way, PRs welcome!

**Comment by aaronbeall** [comment]
Source in TypeScript would be even better! I am not very familiar with Koa's code yet but it looks super simple, maybe I'll take a crack at it.

**Comment by dmytro-lymarenko** [comment]
*+* for TS

**Comment by aaronbeall** [comment]
I submitted a PR awhile back... any feedback, @lourd ?

**Comment by jonaskello** [comment]
One year later... still no typescript?

**Comment by lourd** [comment]
Thanks for the ping @jonaskello, got me motivated to actually act on this. Just pushed a couple more commits to @aaronbeall's PR. If y'all can help review it I'll make sure a new version with TypeScript support gets published this week.

**Comment by jonaskello** [comment]
@lourd Thanks for working on this, and sorry for the somewhat harsh ping :-)

I did a quick review and left a comment in the PR. Other than that I think it looks good.

**Comment by lourd** [comment]
No worries at all, thank you @jonaskello.

I really think there should be some sort of integration tests with a couple of the popular Express middleware libraries to make sure the TypeScript version will actually work with ecosystem. I'm not confident in the functionality without that. Can you or @aaronbeall or one of the other folks subscribed here volunteer to do that?

**Comment by lourd** [comment]
Closed via #13
