### ISSUE TITLE
Publish @next on npm

### ISSUE THREAD

**Issue by tuckerconnelly** [vkurchatkin/koa-connect#5]

**Comment by olconstant** [comment]
Agreed, publish release v2.0.0 on npm.

**Comment by lourd** [comment]
@vkurchatkin, can you give me npm publish access?

**Comment by cyrilluce** [comment]
I have fork this and publish **koa2-connect** on npm, wish this will help you guys :smile: 
P.S. Also has improve compatibility with webpack-dev-middleware and webpack-hot-middleware.

**Comment by lourd** [comment]
Hey @cyrilluce, that definitely encouraged me, thank you. I just published v2.0.0 on npm and I'm very happy to incorporate the code on your fork. If you're inclined to re-merge the projects, please open a PR and we can start the discussion.

**Comment by niftylettuce** [comment]
@olconstant 	Can you please email me? niftylettuce@gmail.com - been trying to get in touch about something re: blogging/tech and can't find your public email anywhere haha, I tried a few I found but they all bounced back
