### ISSUE TITLE
There's no next tag in the npm package.

### ISSUE THREAD

**Issue by gbahamondezc** [vkurchatkin/koa-connect#7]
I tried to install with npm install koa-connect@next and gives me an error, using npm show koa-connect in tags section i can confirm there's no next tag as the documentation says, but there's is a latest tag which is compatible with koa 2, documentation should  be updated.

**Comment by krini** [comment]
This is still an issue...

**Comment by lourd** [comment]
Thank you for the reminder @krini. I've removed references to needing the `next` tag for installation, and mentioning Koa v2 as something special since it's now the stable version. Published as 2.0.1
